spring.application.name=booking-system
spring.datasource.url=jdbc:mysql://localhost:3306/tourism_db
spring.datasource.username=root
spring.datasource.password=pmd123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Disable caching so changes appear immediately
spring.web.resources.cache.period=0
spring.mustache.servlet.cache=false